# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '8888' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 8888
pod 'SDWebImage'

  target '8888Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '8888UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
